### ISSUE TITLE
IQ graph is incomprehensible

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#181]
![image](https://cloud.githubusercontent.com/assets/18272943/23581205/07c30400-0110-11e7-863c-03470b8ca60a.png)

no clear relation between amplitude and gain and the graph,

**Comment by SamuelDeleglise** [comment]
I guess this is clearer like that...
![image](https://user-images.githubusercontent.com/2795320/29373519-d4007b40-82ae-11e7-92a0-6844a29a33ed.png)
