### ISSUE TITLE
specan running continuouos

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#263]
click on restart average > acquisition stops...

**Comment by lneuhaus** [comment]
is this resolved?

**Comment by lneuhaus** [comment]
just tried the specan acquisition again and found a somewhat messed up behavior:
- i set trace_average to 12
- i click "Run single"
- i click "Stop" before acquisition finishes -> Run continuous (4) appears on the continuous button -> what does the (4) mean in this context?
- i click on "Run continuous (4)" -> acquisition restarts
- "Pause" appears (how is this different from stop)? Nothing indicates current number of averages
- some more stranger things
- at some point i get "Pause (12+)" with continuous updates of the data. I then click on "Restart average" and would expect a running acquisition with display ("Pause (1)") on the button, but instead the acquisition stops. 

I believe a critical reading + correction of the logic behind the buttons will eliminate 99% of the confusion here..

**Comment by SamuelDeleglise** [comment]
OK, I can work on that. However, I am not able to launch the software with the current version of develop-0.9.3 

On python 3, I get the error

     C:\Users\Samuel\Documents\GitHub\pyrpl\pyrpl\widgets\spinbox.py in max_num_letter(self)
        326         Maximum number of letters in line
        327         """
    --> 328         return int(np.log10(np.abs(self.maximum))+1)
        329 
        330     def setMaximum(self, val):  # imitates original QSpinBox API

    OverflowError: cannot convert float infinity to integer

Probably due to the values at lines 369/370 of attributes.py

Have you pushed everything to the server?

**Comment by lneuhaus** [comment]
this is the last bug i also had, but it should have been fixed by my commit at 11:38 this morning.
