### ISSUE TITLE
FPGA code compilation / Vivado license

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#272]
I checked and the membranePC still has a valid license for Vivado 2015.4. For now, we can compile the FPGA changes on that computer. 

I for my part have forgotten what to do to get a valid permanent license from Vidado (i have to get a new demo license every 30 days), so I believe other people might run into the same problem. 

I'd like the following: someone who has a good license (@SamuelDeleglise , @jneer, @XueshiGuo) logs into their vivado account and copy-pastes a screenshot of the 2-3 pages with the license overview (can be copypasted directly into this window, ie hit "print screen" on the vivado website and ctrl-v in this window) and we make a wiki section on how to install vivado properly. 

thanks!

**Comment by jneer** [comment]
Apologies! I didn't notice I was assigned this until a few days ago. Haven't been keeping track of all your efforts recently. Glad you got it solved. Also, congrats on the first release!

**Comment by lneuhaus** [comment]
No problem, I just put you there to see whether you were still alive ;)
