### ISSUE TITLE
na traces acquired before end of acquisition lead to failures

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#283]
must use smart scheme for missing data (i.e. dont include them)

**Comment by SamuelDeleglise** [comment]
It looks to me like it is solved. Do you confirm ?

**Comment by lneuhaus** [comment]
I just tried it and get no more error. However, the missing points for an incomplete acquisition are automatically set to zero. I would advocate to simply not insert missing datapoints into a curve. Another option would be inserting nan's, which usually leads to other problems sooner or later. 
Do you agree with not saving missing points?

**Comment by SamuelDeleglise** [comment]
Done, I hope that didn't introduce extra bugs in particular with the pyinstruments interface. I also corrected the way the trace_avg number was incremented (now starts at 0 instead of 1)

**Comment by lneuhaus** [comment]
the fix 858c704 causes a lot of failures in nosetests. im trying to fix that right now, unless you have a better idea..

**Comment by lneuhaus** [comment]
```
======================================================================
ERROR: pyrpl.test.test_hardware_modules.test_pid_na_iq.TestPidNaIq.test_iq_na
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\test\test_hardware_modules\test_pid_na_iq
.py", line 347, in test_iq_na
    c = CurveDB.create(f, data, name='test_iq_na-failed-data')
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\curvedb.py", line 88, in create
    ser = pandas.Series(y, index=x)
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\pandas\core\series.py
", line 245, in __init__
    data = SingleBlockManager(data, index, fastpath=True)
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\pandas\core\internals
.py", line 4070, in __init__
    fastpath=True)
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\pandas\core\internals
.py", line 2685, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\pandas\core\internals
.py", line 109, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 51, placement implies 1

======================================================================
ERROR: pyrpl.test.test_hardware_modules.test_pid_na_iq.TestPidNaIq.test_na
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\test\test_hardware_modules\test_pid_na_iq
.py", line 36, in test_na
    acbandwidth=1000, logscale=True)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\modules.py", line 142, in setup
    setattr(self, key, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 97, in __set__
    value = self.validate_and_normalize(obj, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in validate_and
_normalize
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in <listcomp>
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\software_modules\network_analyzer.py", li
ne 58, in valid_frequencies
    return [freq for freq in obj.iq.bandwidth_options if freq > 0]
AttributeError: 'Iq' object has no attribute 'bandwidth_options'

======================================================================
ERROR: pyrpl.test.test_hardware_modules.test_pid_na_iq.TestPidNaIq.test_pid_na1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\test\test_hardware_modules\test_pid_na_iq
.py", line 143, in test_pid_na1
    logscale=True)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\modules.py", line 142, in setup
    setattr(self, key, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 97, in __set__
    value = self.validate_and_normalize(obj, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in validate_and
_normalize
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in <listcomp>
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\software_modules\network_analyzer.py", li
ne 58, in valid_frequencies
    return [freq for freq in obj.iq.bandwidth_options if freq > 0]
AttributeError: 'Iq' object has no attribute 'bandwidth_options'

======================================================================
ERROR: pyrpl.test.test_hardware_modules.test_pid_na_iq.TestPidNaIq.test_pid_na2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\test\test_hardware_modules\test_pid_na_iq
.py", line 193, in test_pid_na2
    acbandwidth=0, logscale=True)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\modules.py", line 142, in setup
    setattr(self, key, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 97, in __set__
    value = self.validate_and_normalize(obj, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in validate_and
_normalize
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in <listcomp>
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\software_modules\network_analyzer.py", li
ne 58, in valid_frequencies
    return [freq for freq in obj.iq.bandwidth_options if freq > 0]
AttributeError: 'Iq' object has no attribute 'bandwidth_options'

======================================================================
ERROR: pyrpl.test.test_hardware_modules.test_pid_na_iq.TestPidNaIq.test_pid_na3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\test\test_hardware_modules\test_pid_na_iq
.py", line 253, in test_pid_na3
    acbandwidth=0, logscale=True)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\modules.py", line 142, in setup
    setattr(self, key, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 97, in __set__
    value = self.validate_and_normalize(obj, value)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in validate_and
_normalize
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\attributes.py", line 709, in <listcomp>
    key=lambda x: abs(x - val)) for val in value]
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\software_modules\network_analyzer.py", li
ne 58, in valid_frequencies
    return [freq for freq in obj.iq.bandwidth_options if freq > 0]
AttributeError: 'Iq' object has no attribute 'bandwidth_options'

======================================================================
ERROR: pyrpl.test.test_na.TestNA.test_na_running_states
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Leo\Anaconda3\envs\py34\lib\site-packages\nose\case.py", line 1
98, in runTest
    self.test(*self.arg)
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\test\test_na.py", line 39, in test_na_run
ning_states
    assert data_changing()
  File "C:\lneuhaus\gitHub\pyrpl\pyrpl\test\test_na.py", line 29, in data_changi
ng
    return (data != self.na.data_avg).any()
AttributeError: 'bool' object has no attribute 'any'

```

**Comment by lneuhaus** [comment]
the commit just before (83e0092e9adefe6d871ed104d32c62b2933aaf99) only has 1 error, 1 failure (all tests done in python 3.4)

**Comment by SamuelDeleglise** [comment]
weird, it should have been tested... I am running the tests here to compare

**Comment by lneuhaus** [comment]
those commits still contain some other failures due to IIR that have been fixed in more recent commits - just ignore those...

**Comment by SamuelDeleglise** [comment]
OK, I get plenty of errors as well, I am also looking

**Comment by SamuelDeleglise** [comment]
OK, I see the first problem...

We access the curve and data_x via 2 different attributes. It was fine as long as the length of these tables was not constantly changing, but now, if you don't call data_x exactly at the right time, you end up with a different number of points in x and y.

**Comment by lneuhaus** [comment]
some things are pretty clearly wrong (at first look, for example the confusion between _data_x and data_x

**Comment by SamuelDeleglise** [comment]
Yes, data_x is the "variable-length" version of _data_x, but you are right I should change the name to ``data_x_valid``

... what complicates even more the problem is that curve() and run_single() are 2 different ways of getting the curves, but for the moment, curve() will leave data_x unchange, while run_single will make the length of data_x change

**Comment by SamuelDeleglise** [comment]
I foresee that if we keep variable-length array + curve + run_single this is going to be very messy.

**Comment by lneuhaus** [comment]
sounds not very good. I'm not all into your logic right now, but as an "external", I don't see why you force yourself to stick to a fixed-length version of the data array. I can see that you want to easily insert a point when it is acquired, but in that case I smell a typical use-case for a pandas series - which has been a very stable and reliable package since continuumm analytics takes care of it.

**Comment by SamuelDeleglise** [comment]
If we choose to fetch independently x and y values (which is the case right now), it is dangerous to have variable length arrays.

What you suggest is to use a pandas Series to fetch both at the same time. I personally find it adds a dependency that is really heavy for a hardware package...

**Comment by lneuhaus** [comment]
we had that pandas discussion somewhere else if you remember. right now we do have pandas as a dependency, even though we dont (or hardly) use it. ever since anaconda, i find that the pandas dependency is totally negligible to the pyqt dependency.

**Comment by lneuhaus** [comment]
and i believe that the transition from '_data' to 'data' is somewhat the same thing as pandas does

**Comment by lneuhaus** [comment]
but do as you please, im never properly read the acquisition_module code

**Comment by SamuelDeleglise** [comment]
Not to mention that fetching the x-data for every curve, eventhough they might not change between successive acquistions, is an overhead...

**Comment by lneuhaus** [comment]
i dont understand what you mean by 'fetching'. the logic i have in mind is this
- for a na-trace, the full x-axis is essentially fixed with the setup parameters, for a scope and so on as well
- for an incomplete (or full) acquisition, there can be random pairs of x and y values
- but those pairs of values must by all means remain associated together in order to not shuffle x and y data

**Comment by lneuhaus** [comment]
Another option to avoid variable-length arrays is filling the full-length y-array with nan's and ensuring that the plotting logic simply ignores nans

**Comment by SamuelDeleglise** [comment]
In the Virgo dataDisplay, I remember the invalid points are replaced by the values of the last valid point. That's probably to avoid the problems with log-scale and autoscaling of graphs, and to avoid at the same time playing with variable lenth arrays

**Comment by lneuhaus** [comment]
im strongly against that, rather in favor of nans which are simply not plotted...

**Comment by SamuelDeleglise** [comment]
OK I take care of it then

**Comment by lneuhaus** [comment]
for example, if we have the full arrays x, y where y contains a few nan's, we can do this:
```
index = np.isfinite(y)
x_plot = x[index]
y_plot = y[index]
```

**Comment by SamuelDeleglise** [comment]
In fact from what I see, Matplotlib is clever enough to properly deal with nan

    x = linspace(0,6*pi, 10000)
    y = np.sin(x)
    y[1000:].fill(nan)
    plot(x, y)

**Comment by lneuhaus** [comment]
the question is whether pyqtgraph is smart enough, no?

**Comment by SamuelDeleglise** [comment]
If you are concerned about the na widget, it is anyways never trying to plot the full curve at once.

btw, I have pushed the commit... ALL 354 tests are passing in 254 s here (python 3.6)

**Comment by lneuhaus** [comment]
same here: all 354 tests passing in 375 s (python 3.4). Let's see what travis says but already close the issue..
