### ISSUE TITLE
two scopes at the same time (5 total) running - python freezes

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#289]

**Comment by SamuelDeleglise** [comment]
I assigned you because I only have 2 redpitayas available and could not reproduce the bug after a quick try...

**Comment by lneuhaus** [comment]
At the moment i cannot test it either. It is something that happens when a full experiment is running. The question here is rather: is there a conceivable mechanism for a deadlock when two scopes are continuously running in the same ipyhton kernel?

**Comment by lneuhaus** [comment]
Could not reproduce this, it seems the problem got fixed. A code example can be found in #349 a bit doen where up to 4 scopes can run simultaneously.
