### ISSUE TITLE
pyqt4 dependency

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#297]
See my question: https://github.com/ContinuumIO/anaconda-issues/issues/2682
Answer: we should sooner or later upgrade to pyqt5 :(

**Comment by SamuelDeleglise** [comment]
I will try to handle the transition in a separate branch pyqt5

**Comment by SamuelDeleglise** [comment]
Done, I just made a pull request (also I allowed myself to push some minor changes on master because there were some annoying bugs left)
