### ISSUE TITLE
Unittest for test_load_save with scope leads to freezing of nosetests (pyqt5 branch)

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#300]
replace line 17 by line 18 in test_load_save.py, and nosetests will freeze at the test teardown AFTER test_load_save.py... 
something with the scope seems to inhibit proper teardown of the pyrpl instance without deadlock

**Comment by lneuhaus** [comment]
still unclear...

**Comment by SamuelDeleglise** [comment]
I am not able to reproduce this bug. Is this still there ?

**Comment by lneuhaus** [comment]
with the most recent version, nosetests finishes (not without errors but still) in python 3.6, 2.7 and 3.4. So we can assume the bug is gone, possibly due to the cleanup of acquisition_module.
