### ISSUE TITLE
arroseur is down...

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#310]

**Comment by SamuelDeleglise** [comment]
Oups, I forgot to reboot it...

**Comment by SamuelDeleglise** [comment]
In principle, I have rebooted it yesterday night...

**Comment by lneuhaus** [comment]
It seems down again since last night :(

**Comment by SamuelDeleglise** [comment]
It should have been rebooted by Aglantine this morning

**Comment by lneuhaus** [comment]
cool, its working again. Thanks!
