### ISSUE TITLE
Silence the Logger upon repeated messages

### ISSUE THREAD

**Issue by SamuelDeleglise** [lneuhaus/pyrpl#311]
I believe this is a feature that exists for instance in Mathematica:
Whenever a message repeats itself several times, just write in the console that other occurences of the message will be removed.

Maybe there is even support for that in the logging module ?

For instance when acquiring with a too small number of avg with the network analyzer, you get a new Info message after each trace, which is very annoying...

**Comment by lneuhaus** [comment]
https://stackoverflow.com/questions/44691558/suppress-multiple-messages-with-same-content-in-python-logging-module-aka-log-co

**Comment by SamuelDeleglise** [comment]
Done
