### ISSUE TITLE
Access to slow ADCs

### ISSUE THREAD

**Issue by santamaria42** [lneuhaus/pyrpl#367]
Is there a way to read out the slow ADCs on the E2 Extension connectors right now?

**Comment by lneuhaus** [comment]
Currently only through linux I think, that means at least one millisecond
of delay. Is that enough for you?

santamaria42 <notifications@github.com> schrieb am Sa., 12. Jan. 2019,
15:50:

**Comment by santamaria42** [comment]
Yes that is fast enought. I only want to add some analog controllers to the RP.
Thanks for your promt reply.

**Comment by lneuhaus** [comment]
You know how to retrieve the data?

santamaria42 <notifications@github.com> schrieb am Sa., 12. Jan. 2019,
18:56:

**Comment by santamaria42** [comment]
I wanted to use the scpi connection to read them out in combination with Python scripts as in the example on the rp Website https://redpitaya.readthedocs.io/en/latest/appsFeatures/examples/ana-exm1.html
