### ISSUE TITLE
Provide consecutive Curves/Data

### ISSUE THREAD

**Issue by nemace** [lneuhaus/pyrpl#377]
In my use-case 
(meassuring the FWHM, intensity and position of one specific mode of a high-finesse optical resonator a few thousand times per second by sweeping the resonator length repeatedly) 
it is very important to get the data from each possible trigger. 
I did not find any information in the docs or the source regarding this.

Another possible solution would be to be able to get consecutive data (like in the continuous mode) for specific duration using a specific sampling rate . 
This should be possible since the scope widget seems to do this already,  but i was unable to find the correct way to implement this in the docs or source.

**Comment by lneuhaus** [comment]
Hi @nemace,

sorry for my late reply. The scope widget does not really do this right now - in continuous mode, it currently repeatedly downloads the entire scope buffer and displays it. At 50 fps, this gives the impression of a continuous trace of data, but there is no "stitching logic" implemented right now. 

What "specific sampling rate" would be suitable for your implementation? As a function of that, it might be more or less easy to get your use-case working with a continuous streaming mechanism. 

For getting entire scope traces for all possible triggers (your first paragraph), the current version of pyrpl will only work up to rates of the order of 100 Hz.
