### ISSUE TITLE
How to change analog input range to 20V? Please help

### ISSUE THREAD

**Issue by puyaafsharian** [lneuhaus/pyrpl#386]
Hi pyrpl friend,

I am using your fantastic and working SDK for my project and can only use fast analog input configiration of +/-1V. But I need your urgent help to let me know how can I configure the input for +/-20V ??

Best regards,
Pouya, Oslo

**Comment by lneuhaus** [comment]
Hi, no problem in using the +-20V range, but the displayed voltage will remain between +-1V. Thus, to get the correct scope reading, you have to multipy the numbers by 20.
