### ISSUE TITLE
pyrpl-linux: symbol lookup error

### ISSUE THREAD

**Issue by ecdlguy** [lneuhaus/pyrpl#392]
Hi, 

I'm trying to run pyrpl-linux (from sourceforge) on Ubuntu 18.04.3 LTS.
I get the following error:
`./pyrpl-linux: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: drmGetDevice2`
which can be resolved using
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libdrm.so.2`
but then I get the error
`./pyrpl-linux: symbol lookup error: /tmp/_MEIlNqGZB/libmkl_intel_thread.so: undefined symbol: omp_get_num_procs`
and here I'm stuck.

Any ideas? cheers,
Thorsten

**Comment by lneuhaus** [comment]
This will be fixed by #399
