### ISSUE TITLE
Analog inputs and outputs?

### ISSUE THREAD

**Issue by gsteele13** [lneuhaus/pyrpl#401]
Is there any support for the "slow" analog inputs and outputs?

At first it seemed that the AMS module was what I was after, but the code gave me the impression that the Analog I/O is not really implemented? 

```
    """mostly deprecated module (redpitaya has removed adc support).
    only here for dac2 and dac3"""
    addr_base = 0x40400000
```

(I'd like to use them to read out a PT100 sensor...)

It's not clear to me that RP had chosen to remove ADC support, it is still present in their SCPI server: 

https://redpitaya.readthedocs.io/en/latest/appsFeatures/remoteControl/SCPI_commands.html

Thanks,
Gary

**Comment by lneuhaus** [comment]
The ams module allows to set the slow analog PWM outputs dac2 and dac3. The other two, pwm0 and pwm1, can be found in extra modules - see an example here https://github.com/lneuhaus/pyrpl/blob/develop-0.9.3/docs/example-notebooks/pwm-example.ipynb

The slow analog inputs are currently only supported in the branch max_hold_no_iir of PyRPL. There you can find them in the ams module. The input voltage range is -3.5 to +3.5 V. I will soon merge this to master.
