### ISSUE TITLE
numpy fftpack deprecation

### ISSUE THREAD

**Issue by Bruyant** [lneuhaus/pyrpl#417]
Spectrum analyser is not starting due to depreciation of fftpack in numpy >1.17:

"NumPy’s FFT implementation was changed from fftpack to pocketfft, resulting in faster, more accurate transforms and better handling of datasets of prime length. See below under Improvements."

source

https://numpy.org/doc/stable/release/1.17.0-notes.html?highlight=numpy%20fft%20fft

my settings
     active environment : pyrpl-env
    active env location : /opt/anaconda3/envs/pyrpl-env
    conda version : 4.8.3
    conda-build version : 3.18.11
   python version : 3.7.6.final.0
   numpy                     1.18.5           py38h1da2735_0  
   numpy-base                1.18.5           py38h3304bdc_0  

Solution:
    forcing numpy <1.17
    moving to pocketfft: personally I'll try this and maybe submit a PR if it work

**Comment by Bruyant** [comment]
a proposition of fix but it's not backward compatible with old numpy...

https://github.com/Bruyant/pyrpl/commit/a4edf5899a81e45438721398fff2b5a2e23e0f03

**Comment by lneuhaus** [comment]
Thanks so much! I implemented your fix, and will soon merge it into master!
