### ISSUE TITLE
Compatibility with SignalLab250-12

### ISSUE THREAD

**Issue by lizunya1983** [lneuhaus/pyrpl#442]
Hi, is PyPRL API compartible with RedPitaya SignalLab 250-12?

**Comment by lneuhaus** [comment]
No, it's not. I am working on a migration, but the natural order of things will be 
1. merge all open pyrpl PR's
2. migrate pyrpl to use pypga as backend for FPGA design
3. implement SignalLab 250-12 support in pypga
4. Pyrpl would now automaticaly support SignalLab 250-12.
This might unfortunately take a while.
