### ISSUE TITLE
ERROR during bitfile generation

### ISSUE THREAD

**Issue by haectobi** [lneuhaus/pyrpl#445]
Hi,

When trying to do the bitfile generation of the unmodified code I get following Error:

ERROR: [DRC 23-20] Rule violation (INBB-3) Black Box Instances - Cell 'i_dsp/genblk4[4].iir/p_ay1_module/product0' of type 'i_dsp/genblk4[4].iir/p_by1_module/product0/mult_32_32' has undefined contents and is considered a black box.  The contents of this cell must be defined for opt_design to complete successfully.

I am using Vivado 2015.4 on windows 10 and saw on the Xilinx webpage that these versions dont support each other. But I am unsure because the synthesis and simulation work. Could the version be the issue?

Or has anyone else had this Error?

**Comment by lneuhaus** [comment]
I never tested vivado on win10. Could certainly be the issue. Can you test on a different OS, eg Ubuntu booted from a usb stick?

**Comment by haectobi** [comment]
Can you also compile pyrpl with a different Vivado version?

**Comment by lneuhaus** [comment]
not without errors I think. In principle it should be straightforward to migrate to a more recent vivado version, but this will require some modifications.
