### ISSUE TITLE
specan + noise unittest missing

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#59]

**Comment by SamuelDeleglise** [comment]
What exactly do you have in mind ? Integrating the noise spectrum from 0Hz to Nyquist frequency to make sure it's equal to the variance of the noise ?

**Comment by lneuhaus** [comment]
I have tested with a commercial SA that the noise spectrum for
amplitude<0.4V is flat and has a spectral density of amplitude^2/62.5MHz to
within ~5% for frequencies up to 50 MHz. So we actually know the result of
such a spectrum measurement and can confirm that se SA shows the right
spectrum. This is more dtraightgorward than what we acytually have i think

On Jul 2, 2017 1:26 AM, "SamuelDeleglise" <notifications@github.com> wrote:

What exactly do you have in mind ? Integrating the noise spectrum from 0Hz
to Nyquist frequency to make sure it's equal to the variance of the noise ?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/lneuhaus/pyrpl/issues/59#issuecomment-312460950>, or mute
the thread

**Comment by lneuhaus** [comment]
Specifically assert max(abs((spectral density-theory)/theory-1))<0.05 or so

On Jul 2, 2017 8:58 AM, "Leonhard Neuhaus" <l.neuhaus@web.de> wrote:
>
> I have tested with a commercial SA that the noise spectrum for
amplitude<0.4V is flat and has a spectral density of amplitude^2/62.5MHz to
within ~5% for frequencies up to 50 MHz. So we actually know the result of
such a spectrum measurement and can confirm that se SA shows the right
spectrum. This is more dtraightgorward than what we acytually have i think
>
>
> On Jul 2, 2017 1:26 AM, "SamuelDeleglise" <notifications@github.com>
wrote:
>>
>> What exactly do you have in mind ? Integrating the noise spectrum from
0Hz to Nyquist frequency to make sure it's equal to the variance of the
noise ?

**Comment by SamuelDeleglise** [comment]
OK, I have been looking into more details in the calculations and I am now more or less convince the rbw is correct.

However, I think we have some subtle effects with the white noise:

1. When working with the maximum span, there should be no transfer-function correction since the scope is not doing any decimation, however, we do have a non-unity transfer-function correction in this case (that would make sense anyway to take into account some level of filtering by the analog inputs themselves...)
1. When working with a smaller span, I believe the modeling of the decimation transfer function is correct, however, there I also observe an excess noise at high frequency which I interpret as the aliasing of higher frequency noise inside the window.

-> I haven't tried yet to model the second effect quantitatively, but intriguingly, it seems that one recovers a flat spectrum by undoing the transfer_function correction...

**Comment by SamuelDeleglise** [comment]
To confirm this, I made the following observations:

I setup a narrow bandpass filter with an IQ to make sure only a small frequency band contributes to the spectrum, and monitor with in1 the spectrum directly from the noise generator, and with in2, the spectrum after the iq filter.

--> I should get reed of aliasing problems, but still have the improper frequency correction for the maximum span.

--> This is exactly what I observe: I get a flat response when scanning the filter frequency whenever span<65 MHz, but still get the increased spectrum close to 65 MHz for the largest span (in this case, both curves are superimposed at the peak value).

**Comment by lneuhaus** [comment]
> When working with the maximum span, there should be no transfer-function correction since the scope is not doing any decimation, however, we do have a non-unity transfer-function correction in this case (that would make sense anyway to take into account some level of filtering by the analog inputs themselves...)
- I'm obviously against globally applying the inverse analog input transfer function to the scope or the like, since we might measure other signals as well. but if one wants to (i dont mind but wouldnt prioritize this) one could somewhere define the saved / approximated analog transfer function to be manually or automatically applied when needed. 
- If I am not mistaken, however, apart from the above-mentioned 'analog transfer function' (i.e. input lowpass filter for antialiasing), there is also a transfer function associated with the analog-to-digital conversion, i.e. the sample-and-hold procedure. This function depends on whether one 'samples' the input signal every 8 ns or whether one averages it over the past 8 ns or whatever is in between. Without reference I believe to remember that the first case (infinitely rapid sampling every 8ns) is the case that is closer to the reality with the redpitaya board. 
- Next, the question is how we treat the digital signals that are shown on the scope. There is of course a fundamental difference between digital (discrete-time) and analog (continuous-time) Fourier transform, and I believe we are discussing this. I have tried to always consistently leave model everything on the user side as continuous-time (analog) signals, but if this should be impossible here, then we must of course do it (+document it). 
- I believe the transfer function at the highest-sampling rate is related to the sample-and-hold approximation. Is this definitively wrong?

**Comment by lneuhaus** [comment]
@SamuelDeleglise do you want to try to configure the iir filter to use it for the specan? not sure if this is straightforward, but it will validate the iir (gui not tested since its development, filter itself is unit-tested), improve the specan, and give you a headstart to using the iir.
